export const TEST = "TEST";
export const OFFER_ALL_DATA = 'OFFER_ALL_DATA';
export const OFFER_ALL_DATA_SUCCESS = 'OFFER_ALL_DATA_SUCCESS';
export const OFFER_ALL_DATA_ERROR = 'OFFER_ALL_DATA_ERROR';
